services:
  backend:
    image: poc-backend
    pull_policy: never
    # evita di pullare imamagini da internet omonime per sbaglio
    container_name: poc-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/src:/app/backend/src
    ports:
      - 8000:8000
    environment:  # aggiunte key Zucchetti e secre key sessioni
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - PYTHONPATH=/app/backend/src


  frontend:  
    image: poc-frontend
    pull_policy: never
    # evita di pullare immagini da internet omonime per sbaglio

    container_name: poc-frontend
    build:
      context: ./frontend #guarda solo la cartella frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend